FROM python:3.10-slim

WORKDIR /app

COPY vision_requirements.txt .

RUN pip install --no-cache-dir -r vision_requirements.txt

COPY . .

CMD ["streamlit", "run", "topology_vision/topology_vision.py", "--server.port=8502", "--server.enableCORS=false"]
